name: nix-flake-check

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:

  nix-flake-check:

    permissions:
      contents: read

    runs-on: ubuntu-latest

    steps:

      - name: Repository checkout
        id: git-checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

        with:
          submodules: true

      - name: Setup nix
        id: nix-install
        uses: ./.github/composites/nix-setup

      - name: Run flake check
        id: nix-check

        run: nix flake check path:.
